--- 
- 
  name: "Hello Ansible - quick start"
  hosts: localhost
  sudo: yes

  tasks: 
    - 
      name: "Hello server"
      shell: "date >> now.txt"
     
      name: echo hello world
      shell: echo "Hello World!" > bala.txt
