--- 
- 
  name: 'Hello Ansible - quick start'
  hosts: localhost
  tasks: 
    - 
      name: "Hello server"
      shell: "date >> now.txt"
     
    - name: 'copying file modulu'
      copy: src=/root/ansible.txt dest=/root/ owner=root grou=root mode=0644 backup=yes 